project:
  type: website

format: 
  html: 
    theme: default
    tufte: true
    css: styles.css
    include-before-body:
      - _header.html
      - _sidebar.html
    

website: 
  title: "Introdução aos Softwares Estatísticos"
  



